title: <p align="center"> Sushant Sur </p>
logo: /assets/img/mypic.jpg
# description: Minimal is a theme for GitHub Pages.
# show_downloads: true
# google_analytics:
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sushant-sur-b1b98319/">LinkedIn</a> |
  <a href="https://github.com/sushantsur23">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Worked with Dell, Accenture and Travelopia into Analytics projects.
  Currently looking for new opportunities.
  <br>
  </p>


theme: jekyll-theme-minimal
